#!/usr/bin/env bash

export PREMOUNT_POSTGRESQL_ENABLED=1

export PREMOUNT_POSTGRESQL_OUTPUT_DIR='/backup/postgresql'

export POSTGRESQL_SUDO_USER=postgres

export PREMOUNT_POSTGRESQL_DELETE_FILES_OLDER_THAN=20
